package com.potholeiq.model.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.potholeiq.dto.DetectionDto;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;
import org.locationtech.jts.geom.Point;

import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;

/**
 * DamageReport — core entity representing a detected road damage event.
 * Each scanned image that yields a pothole detection produces one DamageReport.
 *
 * The `geom` field uses a PostGIS geometry(Point,4326) column for spatial queries.
 * Hibernate Spatial (hibernate-spatial on classpath) handles the JTS ↔ PostGIS mapping.
 */
@Entity
@Table(name = "damage_reports", indexes = {
        @Index(name = "idx_damage_report_status",   columnList = "status"),
        @Index(name = "idx_damage_report_severity", columnList = "severity"),
        @Index(name = "idx_damage_report_session",  columnList = "scanner_session_id")
})
@Getter
@Setter
@NoArgsConstructor
public class DamageReport {

    public enum ReportStatus {
        REPORTED, VERIFIED, ASSIGNED, IN_PROGRESS, COMPLETED, REJECTED
    }

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(updatable = false, nullable = false)
    private UUID id;

    /**
     * The user who submitted this report.
     * Stored as reporter_id (FK → users.id) in the DB.
     * Use getReporterId() / setReporterId(UUID) for UUID-only access.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "reporter_id", referencedColumnName = "id")
    @JsonIgnore
    private User reporter;

    /** Convenience accessor — returns reporter's UUID without loading the full User. */
    @JsonProperty("reporterId")
    public UUID getReporterId() {
        return reporter != null ? reporter.getId() : null;
    }

    /** Relative path to the original scanned image, e.g. /uploads/images/uuid.jpg */
    @Column(name = "image_url")
    private String imageUrl;

    /** Relative path to a thumbnail (optional, generated by frontend or future service) */
    @Column(name = "thumbnail_url")
    private String thumbnailUrl;

    /** GPS latitude of the detected pothole */
    @Column(name = "latitude")
    private Double latitude;

    /** GPS longitude of the detected pothole */
    @Column(name = "longitude")
    private Double longitude;

    @Column(name = "address_text")
    private String addressText;

    /** Human-readable street address from reverse geocoding */
    @Column(name = "street_address", length = 512)
    private String streetAddress;

    /**
     * PostGIS geometry column — holds the precise geographic point.
     * Used for spatial queries (ST_DWithin, heatmap clustering).
     * Must have PostGIS extension enabled: CREATE EXTENSION IF NOT EXISTS postgis;
     * Excluded from JSON serialization — lat/lng scalar fields are used instead.
     */
    @JsonIgnore
    @Column(name = "geom", columnDefinition = "geometry(Point,4326)")
    private Point geom;

    /** Whether the AI model detected a pothole in the image */
    @Column(name = "has_pothole")
    private Boolean hasPothole = false;

    /** ONNX model confidence score [0.0 – 1.0] */
    @Column(name = "confidence_score")
    private Double confidenceScore;

    /** Bounding box of the primary detection in original image coordinates */
    @Column(name = "bbox_x")
    private Double bboxX;

    @Column(name = "bbox_y")
    private Double bboxY;

    @Column(name = "bbox_width")
    private Double bboxWidth;

    @Column(name = "bbox_height")
    private Double bboxHeight;

    /** Additional detections found in the same image (stored as JSON) */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "additional_detections", columnDefinition = "jsonb")
    private List<DetectionDto> additionalDetections;

    /** Estimated pothole depth in centimetres (derived from severity scoring) */
    @Column(name = "estimated_depth_cm")
    private Double estimatedDepthCm;

    @Column(name = "severity_score")
    private Integer severityScore;

    /** Severity label: MINOR | MODERATE | CRITICAL */
    @Column(name = "severity", length = 20)
    private String severity;

    /** Composite priority score [0.0 – 100.0] used for sorting/dispatch */
    @Column(name = "priority_score")
    private Double priorityScore;

    /** Current lifecycle status of the repair ticket */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    private ReportStatus status = ReportStatus.REPORTED;

    @Column(name = "exif_gps_found")
    private Boolean exifGpsFound = false;

    @Column(name = "source")
    private String source = "COMMUNITY";

    /** Whether an automated complaint email/PDF was sent to the ward office */
    @Column(name = "complaint_sent")
    private boolean complaintSent = false;

    /** Relative path to the generated complaint PDF */
    @Column(name = "complaint_pdf_url")
    private String complaintPdfUrl;

    /** Timestamp when the AI detected the pothole */
    @Column(name = "detected_at")
    private LocalDateTime detectedAt;

    /** Session identifier from the mobile/scanner client */
    @Column(name = "scanner_session_id")
    private String scannerSessionId;

    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
        if (detectedAt == null) {
            detectedAt = LocalDateTime.now();
        }
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }
}
