services:
  - type: web
    name: potholeiq-backend
    env: java
    rootDir: backend
    plan: free
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/potholeiq-0.0.1-SNAPSHOT.jar --server.port=$PORT
    envVars:
      - key: JAVA_VERSION
        value: 17